server:
  port: 8081
spring:
  application:
    name: fps-bus-ms-process-kpi
  profiles:
    active: ${PROFILE:dev}
  main:
    web-application-type: reactive
logging:
  config: classpath:logging/logback.xml
springdoc:
  swagger-ui:
    path: /swagger-ui.html
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
validation-custom:
  app-id-flag: 0
  app-id: ZnBzLWJ1cy1tcy1wcm9jZXNzLWtwaQ==


route-secret: secret-fapeconnect-dev
route-secret-endpoint: https://dev-secret-manager-ws.solucionestifps.com/api/v1/secret
app-key: secretManagerId